### ISSUE TITLE
How to run RT-TEE on NXP LPC55S69

### ISSUE THREAD

**Issue by danielRep** [WUSTL-CSPL/RT-TEE#1]
As per read on the RT-TEE paper, the TEE has also implemented in an Armv8-M-based board, i.e., the NXP LPC55S69. Is this repo responsible to hold the code? How can I build RT-TEE to run on that board?

Thanks.

**Comment by J1nwenWang** [comment]
Hi Daniel,

Thank you very much for your interest in our work. Currently, we are still organizing the code on Cortex-M. Thus, it's not available now.

Sincerely,

Jinwen Wang.
________________________________
发件人: Daniel Oliveira ***@***.***>
发送时间: 2022年8月25日 5:31
收件人: WUSTL-CSPL/RT-TEE ***@***.***>
抄送: Subscribed ***@***.***>
主题: [WUSTL-CSPL/RT-TEE] How to run RT-TEE on NXP LPC55S69 (Issue #1)


As per read on the RT-TEE paper, the TEE as also implemented in Armv8-M-based board, i.e., the NXP LPC55S69. Is this repo responsible to hold the code? How can I build RT-TEE to run on that board?

Thanks.

―

**Comment by danielRep** [comment]
Thank you for the information @J1nwenWang. I will watch the repo to catch-up.
