### ISSUE TITLE
Have you been moved all flight controller into RT-TEE

### ISSUE THREAD

**Issue by zz-fz-john** [WUSTL-CSPL/RT-TEE#12]
as your paper said :in figure 12,the RT-TEE can hold all ardupilot ,have you really achieve it ?If you achieve it ,can you shared your approach about how to modify ardupilot ?

**Comment by n1ngz** [comment]
Thank you for your interest. Figure 12 was a case study, and for evaluation, we did not migrate the entire ArduPilot stack into it, since it will significantly increase the TCB, and it is entirely clear if that is a good security design.
