### ISSUE TITLE
Path is hardcoded into envi_setup.txt

### ISSUE THREAD

**Issue by RichardHabeeb** [WUSTL-CSPL/RT-TEE#3]
[envi_setup.txt](https://github.com/WUSTL-CSPL/RT-TEE/blob/main/optee_examples/hello_world/envi_setup.txt) has `/home/osboxes/rttee_qemu` hard coded, and it causes the build to fail.

**Comment by J1nwenWang** [comment]
This path needs to be changed according to your environment. I have updated README, please refer to the modification of RTTEE_PATH.
