### ISSUE TITLE
Buildroot arch/Config.in.x86 is missing and prevents build from continuing

### ISSUE THREAD

**Issue by RichardHabeeb** [WUSTL-CSPL/RT-TEE#6]
Even though it's not used, the buildroot conf command needs the arch/Config.in.x86 to continue, and it appears to be missing. A workaround used was to `touch arch/Config.in.x86`

**Comment by RichardHabeeb** [comment]
Seems like there's some other missing files. The workaround is to delete the buildroot folder and checkout a fresh one. The tag 2019.02 seems to work. Additionally the build/br-ext folder is missing `board/qemu/overlay` causing buildroot to fail (https://github.com/OP-TEE/build/blob/3.9.0/br-ext/board/qemu/overlay/etc/init.d/S50udhcpc)

Perhaps a more sane solution would to use an approach like the one used originally by OP-TEE: a manifests repo: https://github.com/OP-TEE/manifest/blob/master/qemu_v8.xml

**Comment by J1nwenWang** [comment]
I have added the missing files.
