### ISSUE TITLE
How to run RT-TEE on risperry pi 3b

### ISSUE THREAD

**Issue by zz-fz-john** [WUSTL-CSPL/RT-TEE#7]
As per read on the RT-TEE paper, the TEE has  implemented in an Armv8-A-based board, i.e., the risperry pi 3b. but this repo only hold the code on qmeu . How can I build RT-TEE to run on that board?

Thanks.

**Comment by J1nwenWang** [comment]
First, you need to modify the secure timer-related codes in RT_TEE_Scheduler.c for Pi (it has existed there, just uncomment it). Then you need to cross-compile secure OS (Modified OP-TEE). At last, you need to replace the OP-TEE OS binary which is in /boot directory on your Pi with the output binary. The other procedures such as secure task creation are the same as the procedures on QEMU.

**Comment by zz-fz-john** [comment]
Do you mean the comment start with "pi3 platform " in RT_TEE_Scheduler.c ? I uncomment them ,But report some undeclare error,i.e.,CORE0_FIQ_SOURCE.I don't know the value of this variable

**Comment by J1nwenWang** [comment]
It is used to specify the FIQ source on Core 0. Please feel free to let me know if you have other questions.
